### ISSUE TITLE
could it be show different dataset predictions with the same model?

### ISSUE THREAD

**Issue by airlsyn** [metriculous-ml/metriculous#5]
for example, with the trained model, I would like to display all metrics of the model on different dataset: train-set, valid-set, test-set? 

How to do it?

Thanks a lot

**Comment by airlsyn** [comment]
finally, i figure out how to do that.

```
evaluator = ClassificationEvaluator(class_names=class_names, ...)

evaluations = [
    evaluator.evaluate(
        ground_truth=ground, model_prediction=pred, model_name=name
    ) for name, ground, pred in zip(dataset_names, ground_truths, model_predictions)
]

cmp = Comparison(evaluations)

cmp.display()
```

**Comment by marlonjan** [comment]
Hi @ericxsun, the solution you have figured out is great. I don't think there is a simpler way to do it currently.
