### ISSUE TITLE
Error running compare_classifiers 

### ISSUE THREAD

**Issue by raquelhortab** [metriculous-ml/metriculous#7]
I am running `compare_classifiers` in a ipynb and I am getting this error

```
/metriculous/_comparison.py:333, in _html_quantity_comparison_table.<locals>.stylish_table_html(df, highlight_fn)
    331 df_styled = df_styled.apply(highlight_primary_metric, axis=1)
    332 if highlight_fn is None:
--> 333     return df_styled.render()
    334 else:
    335     return df_styled.apply(highlight_fn, axis=1, subset=df.columns[1:]).render()

AttributeError: 'Styler' object has no attribute 'render'
```

my code is:

 ```
metriculous.compare_classifiers(
        ground_truth=labels,
        model_predictions=[outputs],
        model_names=["..."],
        class_names=["Negative", "Positive"],
        one_vs_all_figures=True, 
    ).save_html(path)
```

just wondering if someone has the same problem or knows how to solve it

**Comment by raquelhortab** [comment]
It seems I had to downgrade pandas to 1.5.3 

(credits: https://stackoverflow.com/a/76419416/6878997)

**Comment by marlonjan** [comment]
Thanks for reporting the issue and sharing your fix, @raquelhortab. I will hopefully find some time soon to make it work with the latest Pandas version.

Let me me know if you have any other questions or run into any issues. Thanks
